server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

session:
  enable: true
  black-list:
    - admin
    - user
  black-list-providers:
    - by.vitikova.session.provider.impl.DefaultBlackListProvider
    - by.vitikova.session.provider.FileBlackListProvider
  session-provider-url: "http://localhost:8081/api/v1/sessions"

black-list:
  path: classpath:list.txt

springdoc:
  swagger-ui:
    enabled: true
    path: /api/doc/